=== TradeTrust/tradetrust-certificate/schema/1.0/schema.json
{
    "$id": "tradetrust/v1.0",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "$template": {
        "type": "object",
        "properties": {
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          },
          "required": [ "name", "type", "url" ]
      },
      "description": {
        "type": "string"
      },
      "issuedOn": {
        "description": "The date that this certificate was issued by the issuer(s)",
        "type": "string",
        "format": "date-time"
      },
      "certificateType": {
        "type": "string"
      },
      "issuers": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "address": {
              "type": "string"
            },
            "country": {
              "type": "string"
            },
            "email": {
              "type": "string",
              "format": "email"
            },
            "phone": {
              "type": "string"
            },
            "certificateStore": {
              "type": "string"
            }
          },
          "required": ["name", "certificateStore"],
          "additionalProperties": true
        },
        "minItems": 1
      },
      "recipient": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          }
        },
        "additionalProperties": true
      },
      "additionalData": {
        "type": "object"
      }
    },
    "required": ["issuers"],
    "additionalProperties": true
  }

=== TradeTrust/tradetrust-certificate/schema/1.0/sample.json
{
    "id": "ABCXXXXX00",
    "$template": {
      "name": "CUSTOM_TEMPLATE",
      "type": "IFRAME_RENDERING",
      "url": "http://localhost:3000/rederer"
    },
    "description": "A Certificate",
    "issuedOn": "2018-08-30T00:00:00+08:00",
    "certificateType": "Certificate of Origin",
    "issuers": [{
        "name": "DEMO STORE",
          "address": "Changi Singapore -123456",
        "country": "Singapore",
        "certificateStore": "0x9178F546D3FF57D7A6352bD61B80cCCD46199C2d"
    }],
    "recipient": {
        "name": "Reciepient Name",
        "address": "Sydney Australia",
        "country": "Australia"
    }
}
